# Individual Therapy Sessions

## General Points

* Unless you're told by Jamie, all your clients are general clinic clients and _not_ in DBT.  They are simply being seen under the umbrella of the DBT Clinic at CLU.  They are receiving behavioral therapy.

## First Session Checklist

1. Review Jamie's Safety Planning _[Presentation](https://speakerdeck.com/jdbedics/clu-clinic-orientation-on-safety-planning)_ before meeting with client.  Conduct safety planning as needed. 
    * Always carry the *essential sheets* with you to every session.
2. Checklist:
    * If not done already, set fee. Ask client to bring in proof of income.
    * Do not bring up or mention reduced fee option. If asked, ask the reason and tell them that you will talk to your supervisor.
    * If you're collecting the fee remember to always collect the fee at the beginning of session.
    * Remind them of 24-hour policy for missed sessions or they will be charged.  Charges occur regardless the reason. I often tell them if they have any reason to believe they will miss then call and cancel. 
    * Review confidentiality and privacy.  
    * Ask if they are hoping their records will be used for anything in the future.
    * Ask if they would like for you to talk to someone important to them about their treatment.
    * Orient them to the OQ and help make it easy for them. 
    * Confirm the phone number on file and ask if you can leave a message on their phone if you have to call about logisitics.
    * Remind them that you start at the top of the hour and sessions last 45-minutes.  You can tell them that you manage time and will look at the clock and comment on time as you proceed.  The goal is to make sure they are getting what they want out of the session and are covering everything they intended to have covered.
    * Complete the DBT General Note and start drafting the treatment plan using the CLU template on Titanium.

3. You're allowed to take written notes, use a clipboard, and write on the white board during all sessions.  

## Continuing Sessions

1. Set the recording up early.  Minimize the screen or turn the monitor off.
2. Do not start the session until your client completes the OQ.  
    * Help your client become successful at completing the OQ. Support and encourage and help them remember _how_ to do it. 
3. You might have a therapist in the room before you that ends their sessions late.  Ask them if they plan on continuing to do that in the future.  If so, try to find another room.  If there is no other room, or you'd rather not have that option, talk to Jamie or clinic staff.
4. Complete all notes within *one* week. 
5. Use the DBT General Note for individual sessions.  This is the standard note for your clients when you are supervised by Jamie. 

## Missed Individual Sessions

1. If a client misses a session, call and leave a voicemail following the guidelines in the section on [phone contact](phone-contact-with-clients.html).
2. Write a note for all sessions, even canceled.  Be clear what you did as a result. See the section on [phone notes](phone-contact-with-clients.html).
  

## Setting Goals

It is not your clients job to come into session with goals.  Instead, listen to your clients' concerns and attempt to make them into solvable problems. You never have to use the term _goal_ or ever ask your client _What's you're goal_?  The goals naturally reveal themselves as you listen to what's on your clients' minds. It's your job to rephrase their statements into something like:

    `It sounds like there are times when it's really hard for you to say no? Do you think that would be helpful for us to get our heads around and come up with some solutions?`

## Termination of Treatment

* After 2-3 sessions, let your client know you're plan for intervention along with a timeline for termination.
    * If you're not following an exact protocol then I often make a fairly aribtrary timeline.  For example, if we start on Sept 1st then I'll set a time to end right before Thanksgiving.  
* Let your client know that treatment will be reassessed at that point and could be extended if the client would like to address additional areas.
* When there is a a month left in treatment, remind the client every session that treatment is ending in order to focus your time. 
* In _DBT only_, discuss the concept of ex-therapist for life. 

## Call or text Jamie

* Please do not hesitate to call or text Jamie with any concerns or questions.