# Commitment to DBT Practicum

**Joining Team**

All new members to a DBT Team need to have a commitment session.  This is true even if someone used to be on team but is re-entering.  Often, the last person committed commits the newest member. 

1. The primary commitment is to be on the team and to participate in the training - do your very best to learn DBT.

2. To keep the agreements of the team, especially remaining dialectical.

3. Willing to ask the team for permission when you want to go out of town. 

4. Willing to stay in town if your client is in acute state of crisis and it is not in the best interest of the client for you to leave town.

5. Call out "elephants in the room."

6. Be willing to give clinical advice to people that have more experience than you (including your supervisor).

7.	Function as a therapist in the group (to the group) and not just be a silent observer or a person that only speaks about their own problems.

8.	To have the humility to admit your mistakes/difficulties and the willingness to have the group help you solve them.

9.	To be nonjudgmental and compassionate of your fellow clinicians and clients.  To ring the bell of nonjudgmentalness to remind yourself to not be judgmental.  The bell is a reminder and not a sensor.

10.	To properly assess the problem before giving solutions.

11.	To be willing to go through a chain analysis even though you were only 31 seconds late and you would have been there on time if it wasn't for those traffic lights on Lynn or the parking around the Bell House.  Show up on time or call.

12.	If you feel that the consult team is not being useful or you don't like the way it is being run, to say something about it rather than silently stewing in frustration. 

13.	Be prepared to feel burnt out, frustrated, tired, overworked, underappreciated, hopeless, ineffective and yet - to carry on (easier committed than done, of course).

14.	Participate in team by doing the roles of Leader, Observer, Note Taker, Mindfulness and Phones.

15.	No one can be on team and be unavailable to see a patient.  Know your limits and also be flexible.

16.	Be willing to be responsible for the outcomes of ALL clients on the team; agree that if a client seen by any therapist on the team dies by suicide, you will always say "yes" when asked if you have ever had a client die by suicide. 

    a. Note that this is not a minor responsibility to worry about the other therapists and clients on the team; in a way to function as a supervisor as well.

17.	The best question to ask the other team members is "What experiences have you had that seriously tested your commitment to the team and how on Earth and why on Earth did you still keep your commitment?"

18.	Willing to be on call 24/7 for your clients in comprehensive DBT only.

19.	Willing to not miss more than 2 weeks of therapy with an individual comprehensive DBT client during the entire practicum.

20.	A person may not stop being on the team while they have a comprehensive DBT client.

21.	Watching videos of skills class is part of the practicum and not part of team.

22. Complete all the readings for DBT related coursework and be an active participant in all classes. 

