# Individual Therapy Sessions

## General Clinic

Unless you're told otherwise by Dr. Bedics, all of your clients are general clinic clients and _not_ in DBT per se.  They are simply being seen under the umbrella of the DBT Clinic at CLU.  They are typically receiving behavioral therapy and you are being supervised in behavior therapy based on the DBT manual.

## General Procedures and Professionalism

Your performance and evaluation in the practicum is largely a reflection of your professionalism. 

1. Please pay attention at the clinic orientation and be aware of the clinic's policies and procedures. When you have a clinic question you should refer to orientation materials prior to asking staff. 
2. Plan to be early for all your appointments. The parking at Westlake is often full and challenging to find a spot. Give yourself time.
3. Be polite and respectful to all staff.  I frequently ask staff about your interactions with them. 
4. End all client sessions on-time, at :45 past the hour. Clinicians need to set-up after you.  This means you need to start winding down your sessions but :35 past the hour. 
5. You should not talk about your clients openly in the office or outside of purposeful and intentional consultation with people who have a responsibility to that client (i.e., Dr. Bedics, the clinic director, on-call supervisor).  Feel free to call Dr. Bedics to discuss your cases at anytime.  Simply text Dr. Bedics that you would like to talk but _do not_ include a client name or information.
6. Dress appropriately at the clinic.  All tattoos must be covered (including feet).  The rule is business casual.  No need for ties or anything that formal.  See clinic policies.  The best is to be conservative and boring.  

## First Session Checklist

Review Jamie's **[Suicide Training Presentation](https://speakerdeck.com/jdbedics/clu-2018-community-counseling-safety-training)** before meeting with clients and be prepared to conduct safety planning as needed. Keep the *essential sheets* with you and ready for every session.
   
**Checklist:**

I recommend printing this page our and bringing with you to the first session.  Check the list off as you accomplish each task.

  * Welcome the client and orient them to the uniqueness of the structure of the day (See Suicide Training Presentation)
    
  * Remind client that they are being recorded and that the only person to see the tape is your supervisor.
    
  * Review confidentiality and privacy.  
    
  * Establish the fee and ask the client to bring in proof of income.  Do not bring up or mention a reduced fee option. If asked about a reduced fee then ask the reason and tell them that you will talk to your supervisor and clinic director.  If they are a transfer client than review their existing fee. If it is below the minimum, then ask them the reason.  Discuss on team.    

  * Remind them of 24-hour policy for missed sessions or they will be charged.  Charges occur regardless the reason. Tell them to call ahead if they have any reason to believe they will miss or are even slightly under the weather.  It is best to be cautious to avoid the automatic charge. 

  * Ask if they are hoping their records will be used for anything in the future or sent to any external person.

  * Ask if they would like for you to talk to someone important to them about their treatment.

  * Orient them to the OQ and answer their questions.

  * Confirm the phone number on file and ask if you can leave a message on their phone if you have to call about logistics.

  * Remind them that you start at the top of the hour and sessions last 45-minutes.  You can tell them that you manage time and will look at the clock and comment on time as you proceed.  The goal is to make sure they are getting what they want out of the session and are covering everything they intended to have covered.

  * Orient to behavior therapy.  Tell the client that you conduct short-term problem solving therapy.  Sessions range from 8-10 weeks.  The client can renew after the initial block of sessions.  You can validate that this is likely different from their expectations or therapy that they have had in the past. The first few sessions are unusual as they involve getting to know each other and the completion of the intake form.  After several sessions, you and client review progress and  agree on termination/renewal time.

Students should feel free to save this checklist as a PDF and print this page out for each new client. 

3. You're allowed to take written notes, use a clipboard, and write on the white board during all sessions. By default, use these methods sparingly and only as a means to help you engage the client in the spirit of problem solving. 

## Continuing Sessions

1. Set the recording up early. Minimize the screen **and** turn the monitor off.
2. You might have a therapist in the room before you that ends their sessions late. If that's the case, simply ask them if they plan on continuing to do that in the future.  If so, try to find another room.  If there is no other room, or you'd rather not have that option, talk to clinic staff, the clinic director, or Dr. Bedics.
3. Review the OQ _prior_ to seeing your client. You should always comment on the OQ. Examples include:
    * High or Moderate distress with no change in status from baseline
    * Any note of an increase in a critical item 
    * Significant improvement from baseline
5.  Set a collaborative agenda. Comment on the OQ in doing so. The simple act of asking your client about the OQ shows its importance to you and is often corrective by itself.
5. Complete all notes within *one* week. 
6. Use the DBT General Note for individual sessions.  This is the standard note for your clients when you are supervised by Jamie. 

## Setting Goals

Creating solvable problems from your clients' stated concerns is one of the most important and challenging parts of conducting treatment. Further, this is an ongoing process that does not end with the first few sessions.   The best mindset a therapist can have is to always ask "What does my client need?" or "What would have to be different for my client to create the life they want for themselves?"  These are hard questions for anybody to answer about themselves. 

You will help the client by modeling how to reframe your clients' concerns in a solvable manner. Inevitably, this well help lead to realistic change which will likely also involve some distress tolerance around what _cannot_ be changed in their lives.    

Lastly, you never have to use the term _goal_ or ever ask your client _What's you're goal_?  The goals naturally reveal themselves as you listen to clients' concerns. It is your job to rephrase their statements into something like:

    `It sounds like there are times when it's really hard for you to say no? Do you think that would be helpful for us to get our heads around and come up with some solutions?`

The therapist is then responsible for following up and revising during the course of treatment. 

## Termination of Treatment

As a default, tell your client that you conduct short-term problem solving therapy.  Sessions last between 8-10 sessions with an option to renew.

* After 2-3 sessions, let your client know your plan for intervention along with a timeline for termination.
    * If you're not following an exact protocol then I often make a fairly arbitrary timeline.  For example, if we start on Sept 1st then I'll set a time to end right before Thanksgiving.  
* Let your client know that treatment will be reassessed at that point and could be extended if the client would like to address additional areas.
* When there is a a month left in treatment, remind the client every session that treatment is ending in order to focus your time. 
* In _DBT only_, discuss the concept of ex-therapist for life. 

## Missed Individual Sessions

1. If a client misses a session, call and leave a voicemail following the guidelines in the section on [phone contact](phone-contact-with-clients.html).
2. Write a note for all sessions, even canceled.  Be clear what you did as a result. See the section on [phone notes](phone-contact-with-clients.html).
  

## Call or text Jamie

* Please do not hesitate to text Jamie to discuss a case.  Do not include any identifying information in the text.