# Contact with Providers/Family

## General Information: 

You are responsible for maintaining the confidentiality of your clients' records.  Please do not view records or discuss cases with other providers who are not associated with the case.  

*General Tips*

* Do not leave titanium unattended in any work area.
* Do not look in files that are not assigned to you.
* If you uncover protected health information (PHI), then do your best to protect the information and alert staff.
* Turn Panopto off after each session.

## Conversations in the Clinic (Water Cooler Talk)

It's a natural urge to want to dicuss clients in the clinic especially if your anxious. Please avoid doing so and you'll be noticed in a good way.  The time for consultation is in supervision or on team. Consultation should be well thought out and purposively planned with a specific goal in mind. Check with Jamie if you have any concerns.  

* If someone asks you about a client say: _"Sorry, I can't talk about my clients without consulting my supervisor"_"
* Do this by default.  It's best to be <strong>overly</strong> cautious.


## Email and Printed material 

* Never include your client's name in an email.
* Do not discuss your client in any detail in an email or text message _even if_ de-identified.  Instead, email or text that you'd like to talk about a client.
* Never take material relatd to the client outside of the office.

## Client Requests that you Talk to other people (provider, family, etc.)

1. Say, okay, and that you need to talk to your supervisor to confirm the procedures.
2. Ask yourself what is the reason for the contact.  What purpose would it serve?
3. If you complete a release of information, specify what exactly you'd like to have accomplished and by what day/time.  
4. Always make clear that the release will expire after: 
    a) A certain goal is accomplished and/or 
    b) A certain time has passed by. 


