# DBT Skills Training Class

## General Requirements

Participating in the DBT Skills Class with Jamie is a privilege. There is limited availability and it will add significantly to your workload. Below are the pre-requisites and responsibilities for participation in the skills class.  

#### Prerequisites for DBT Skills Class
1. Purchase the <a  href="https://www.amazon.com/DBT-Skills-Training-Manual-Second/dp/1462516998/ref=dp_rm_img_0">DBT Skills Training Manual</a> along with  <a  href="https://www.amazon.com/Skills-Training-Handouts-Worksheets-Second/dp/1572307811/ref=sr_1_1?ie=UTF8&qid=1503937160&sr=8-1&keywords=dbt+skills+training+handouts+and+worksheets+second+edition">DBT Skills Training Handout and Worksheets</a>. 
2.  Watch a minimum of two DBT Skills Classes saved on Panopto (Videos Assigned by Jamie)
3.  Retrospectively, create an agenda for each group that follows the template on the Google Drive and send to Jamie.  
4. Take notes on the sessions and submit to Jamie.
5. Rate the two videos using the weblink provided to you by Jamie.

#### Responsibilities during Skills Class

At any given time, a total of two students can participate in the Monday night Skills Class with Jamie. One student is a co-leader and one student completed notes.

1. Co-leaders conduct mindfulness.  
    * Each week prepare a mindfulness that is emailed to Jamie by Sunday at 5:PM.
2. Co-leaders write a practice agenda for the teaching portion of the class.
    * You'll be required to outline and submit a practice agenda based on your reading of the teaching manual by 5PM on Sunday before the class.
3. Co-leaders check on late clients and call clients who missed class with the exact HW from the week. 
4. Only the leader and co-leader participate and speak in class. 
5. The note-taker writes all the group notes (see below).
6. All student therapists complete the CLU DBT Skills Training Adherence Checklist after class. 

## Group Notes

Please follow these instructions for completing the DBT Skills Group note.  Two separate groups notes are required in Titanium for the DBT Skills Group.

**Part I. Create and Distribute**

1. Go to your task list and click on DBT Group Note. Follow the template to fill out the note.
2. Once you have completed the note, click “save”.
3. Next, select “distribute” on the top right of the note menu. Select the option to distribute the note to all clients in the skills class.

**Part II. Create and Compose Individual Note**

1. Go back to your task list. There should be additional tasks that have been created for each group member.
2. Click on the client’s note to open-up the task. The note that opens-up should be the previously entered group note that has now been attached or distributed to the individual client’s file.
3. In the “Note Type” bar, select “DBT Individual Group Note”. Titanium will ask if you would like to insert the new template. Select “Yes”.
4. The template for the Individual Group Note will now appear above the previously entered DBT Group Note.
5. Add the group co-leader's name following the “&” symbol on the second line and complete the template.
6. After completing the template (top portion) add the date of the next appointment.
7. Press “Enter” to move down the portion of the Group Note starting with “Session Date”
8. Add `************` between the Group Note and the Individual Note so it is clear where the Individual Group Note ends and the Group note begins.
9. Sign each completed note individually and send to Dr. Bedics

**Part III. Remove Original Group Note**

1. Once you have confirmed each DBT Individual Group Note contains both the DBT Group Note and the Individual Group Note write up, go back into you task list and open-up the original DBT Group Note.
2. Click OK on the box that pops up stating it is the original group note that has been distributed to the group members
3. Click the “save” button on the top left of the note, then click the “delete” button. Confirm you would like to delete the note by clicking “yes” in the box that appears.

Thanks to Andre for putting this together!
## Jamie's Tips for Skills Training

The following are general tips for the overall running of the DBT Skills Class. Specific tips for each module is located in the Google Drive.

## General Tips for Skills Training

* If you purchased the books, the handouts and worksheets on PDF can be retrieved at: <a  href="https://www.guilford.com/skills-training-manual">Guilford Press</a>. You’ll have to register with Guilford but it’s free. 

* Managing time and setting the frame is important.
    * Do your best to start and stop on time and make those decisions clear to the group prior to clients entering group.  
* Be sure to let clients know that if they are late for class they are to wait in the waiting room and we will come and get them after mindfulness (~10-minutes into class) and after HW review (~40-Minutes into class)
* We often have snacks at break.  Twizzlers, pretzels, and tea for some reason.  Obviously this is optional.

### Mindfulness Tips (5-10 Minutes)
<p>

* Be a <strong>leader</strong> of mindfulness.  This means practice beforehand, have your script ready, and be confident and clear when you teach.  Try not to read your example. 
* Tell a story. Example: 

    `“I like hiking and this past weekend I was out for a hike on Mt. Hood.  My friend came with me and really loves trees.  I never noticed the differences between a Doug Fir, Cedar, or Spruce and had fun picking them out.”`
</p>

* Have a clear objective. Example: 

    `“Today, I brought in pictures of a Doug Fir, Cedar, and Spruce.  I’m going to pass them out and I want you to use your describe skills to notice and jot down any differences you see.”`

* Remind about gentleness towards oneself. Example: 
    
    `“You may notice your mind wander to other areas of your life or to your neighbor.  Do your best to notice that and come back to your task.  The mind will wander.  The best we can do is notice and bring it back to our goal. Make sense? Any questions?”` 
    
* Pro Tip: Do not pass out material until you're done with the instructions.  They'll be distracted!
<br>

* Ring bell and check-in. Example: 
   
    `“How was that?” “Did you notice your mind wander? Were you able to bring it back?”`
<br>

* Don’t make it therapy.  Move people along. Co-leader and Leader share too. Leader shares last.  

    * Leader: Resist the urge to comment on how it’s challenging to lead mindfulness while at the same time doing mindfulness. You could do this every session if you really think about it.</p>

### Practice (HW) Review Portion of Class
<p>
1. Remind class what the practice was from last week.
2. Ask for a volunteer to start.

<strong> If Client did not complete practice</strong>:

* Complete a Missing Links Analysis (General Handout 8)
    * Did you know what to do when you left? If yes, then proceed to next.
    * When you left, did you plan doing it? If yes, then proceed to next.
    * Did you remember? If yes, then proceed to next.
    * What happened when you remembered?

* Does not have to be an averse affair.  Just see if you can figure out with some curiosity, interest, what got in the way.   

* Ask if they used other skills they found helpful. I do this to find something to support and encourage. Be careful not to overly reinforce them. 
</p>
<strong>Always Try and Do the Following</strong>:
<p>
* Be behaviorally specific by highlighting thoughts, feelings, behaviors, or bodily sensations
* Manage time. Know your stopping point.
    * Co-leader can help. 
* Keep an ear open for any practice that could lead to a discussion of destructive behavior. 
  * I say things such as:
  
    `“Hold on one second, just checking but is this something that you can share with the group?”`
  
  * I sometimes start off practice (HW Review) with a reminder by saying: 
  
    `“Anybody have any practice that they want to share and that’s appropriate to share with the group?”` 
    
  * The same can be said if a parent or kid starts to share about the other the party.  You can say:
  
    `“Hold on, This sounds like it’s about <other person in room>.  Generally we avoid that in class. <Other Person>, do you know about this and is this okay for them to share? Generally, we want to avoid practice involving other people.”`
    </p>

Common problems to keep an eye out for include:

    * Clients practice their skills in high SUDS situtations only
    * Clients do not write down their assignments

* High SUDs:  Remind clients at the end of every class that they are to practice in low SUDs situations so they can master the skill _first_ prior to using them in the most important situations in their lives.  

* Improve HW Compliance:  Give yourself enough time to help clients start the assignments at the end of class.

### Teaching Portion of Class
<p>
1. Orient Group to Handout: `“Okay group, turn to Handout ##”`
    * Co-leader can walk around and make sure everyone is okay

2. Provide a rationale for why clients would benefit from learning the skill. 
    * Typically done by connecting how the biosocial model fits with the skill being taught.
      `“Have you ever noticed that…”`

3. <strong>Always</strong> have at least on hands-on practice in class and have multiple examples ready to go.
    * Here’s where you can be creative and do your thing.
    * The DBT Teaching Manual has great examples.

4. Be behaviorally specific throughout
    * When you validate, pay attention to the thought, feeling, or behavior and name it as such.
    * Same when you make a correction.

5. Give yourself enough time to assign HW.
    * Know and plan to end with enough time to adequately cover HW and to troubleshoot what can get in the way. Ideally, get them started.
      
      `“What is your plan?” “What can get in they way?  I know you sometimes struggle to remember with your busy schedule.  How will you manage that this week?”`
      
      </p>

### Observations (Final 5-minutes)

1. If the day was busy, chaotic, you can end with something relaxing or help them prepare for what to do after session
    * Depending on class, you can give this 10-minutes if you really want to emphasize self-care after group
    * Called a wrap around procedure.
2. In the absence of problems we do observations: `“Okay group, observations.”`
    * Clients can observe they were tired or that you’re wearing a blue shirt, etc. 
    * Leader goes last and should try to say something supportive or encouraging about the group as a whole.  Something more “Yoda” like than what we expect from the clients.
</p>

