# Phone Contact with Clients

## Missed Session
If a client misses a session then call the client and leave a voice-mail after 20-minutes of waiting.  

* Do not say the name of the clinic in the phone message unless the client confirmed that it's okay to do so at the initial meeting.  
    * Instead, by default say something like:
  
     `“This is < _your first name_ > calling.  We had an appointment at 11:00AM.  I wanted to check-in and make sure everything is okay and to confirm our next appointment.  Also, since I didn't hear from you in 24-hours, I wanted to remind you that you'll be charged for the missed session.  I just didn't want you to be surprised the next time you come since you'll being paying for two sessions. Also, please let me know if you have any concerns. Please call to confirm your next appointment by Friday at 5PM. Just leave me a message.  If I don't hear from you by that time then I'll open your slot.  I don't want you to be charged for another missed session"`
      
  * Write a note based on clinic procedures. For example:

      `Client did not show for individual appointment.  Therapist called client and left a message for client to call and confirm the next appointment.  Therapist also informed client in message of late fee charged.  Next appoint is on DATE. Client was asked to call therapist by DATE at 5:PM to confirm next appointment to avoid any additional charges.`

##  You call the client but someone else picks up.

`"Hi. Is <*client name*> there? No, no message.  I'll try again.  I can't say who this is but thank you.  I'll try again."`

##  Someone calls (or emails) you about the client :

`"I hear your concern, I cannot confirm that someone is or is not a client in the clinic and so I cannot respond to your questions.  If you are concerned for safety, then I can provide general recommendations."`

## Phone Coaching as an intervention

Unless you have approval by Dr. Bedics for phone coaching in DBT, then you do not use the phone for anything but scheduling with your client.  

