# Students


The following students have completed or are completing the full DBT Practicum at CLU.

### Current DBT Practicum Students

**2021-2022**

Madison Pappous, Jatsiri Carrillo Cuevas, Rachael Karp


### CLU DBT Practicum Alumni

**2020-2021**

Kelsey Hawthorne, Illiana Favila-De la Trinidad, Katie Patel, Jose Rios 

**Fall 2019** 

Pooneh Asgari, Kate Diasamidze, Stephen Docherty, Kaylee Jones, Shannel Kassis, Savannah Winterstein

**2018-2019** 

Sarah Amato, Brian Knoll, Melinda Moreau, Brandon Morrison, Nico Sirianni, Andre Petrossian, Natalia Witkowska

**2017-2018** 

Madison Bailey, Ricardo Cornejo, Kimberly Johnson, Joshua Lorimer, Sarah Rosas (MFT)

**2016-2017**

Rebecca Dreiling, Jon Fledzinskas, Colin Goodwin, Brandon Heimburg, Monique Loza, Dana Schmidt

**2015-2016**

Holly McKinley, Kayla Nelson

**2014-2015**

Ebony Christian, Sodah Minty, Desiree Wilson

**2013-2014**

James Battles, Jami Kerr, Amy Scott

**2011-2012**

Carli Tansey, Ashley Riberio, Bonnie Brown, Patricia Wright, Jackie Henretig, Ivy Luc
